# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a29e3a0a01a7d81f9432854a01fc007a2cf287ce650cefecae79424046e1ba1a84ec0d7599a9cdd45749395b538287810acc14f1790409b6db0c091773a91fdf

test:
  secret_key_base: 7d565df8baa745dadcebdcc3e03a2b0b9e6908c390901ac8a3a6921c97bb6e7b6cfaa7aa4156e1eb0ab06cae1e6dda52ce060218158b1279800b7a1e395d30af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
